### ISSUE TITLE
Error: coverage length mismatch for Java / Cobertura

### ISSUE THREAD

**Issue by koraktor** [codeclimate/test-reporter#204]
I tried using test-reporter with [Mavanagaiata](https://github.com/koraktor/mavanagaiata). I had quite a few problems regarding Cobertura that I was able to work around using e.g. `format-coverage`, but this problem seems to persist:

```
../../../cc-test-reporter format-coverage -t cobertura -d ../../../target/site/cobertur
a/coverage.xml
DEBU[0000] coverage path ../../../target/site/cobertura/coverage.xml
DEBU[0000] using formatter cobertura
DEBU[0000] checking search path ../../../target/site/cobertura/coverage.xml for cobertura formatter
DEBU[0000] couldn't load branch from ENV, trying git...
DEBU[0000] couldn't load commit sha from ENV, trying git...
DEBU[0000] couldn't load committed at from ENV, trying git...
DEBU[0000] getting fallback blob_id for source file com/github/koraktor/mavanagaiata/git/AbstractGitReposit
ory.java
DEBU[0000] getting fallback blob_id for source file com/github/koraktor/mavanagaiata/git/CommitWalkAction.j
ava
DEBU[0000] getting fallback blob_id for source file com/github/koraktor/mavanagaiata/git/GitCommit.java
DEBU[0000] getting fallback blob_id for source file com/github/koraktor/mavanagaiata/git/GitRepository.java

DEBU[0000] getting fallback blob_id for source file com/github/koraktor/mavanagaiata/git/GitRepositoryExcep
tion.java
DEBU[0000] getting fallback blob_id for source file com/github/koraktor/mavanagaiata/git/GitTag.java
DEBU[0000] getting fallback blob_id for source file com/github/koraktor/mavanagaiata/git/GitTagDescription.
java
DEBU[0001] getting fallback blob_id for source file com/github/koraktor/mavanagaiata/git/MailMap.java
DEBU[0001] getting fallback blob_id for source file com/github/koraktor/mavanagaiata/git/jgit/JGitCommit.ja
va
DEBU[0001] getting fallback blob_id for source file com/github/koraktor/mavanagaiata/git/jgit/JGitRepositor
y.java
DEBU[0001] getting fallback blob_id for source file com/github/koraktor/mavanagaiata/git/jgit/JGitRepositor
y.java
Error: coverage length mismatch for com/github/koraktor/mavanagaiata/git/jgit/JGitRepository.java
```

I’d guess `JGitRepository.java` ([source](https://github.com/koraktor/mavanagaiata/blob/7bd93918cd89f857b7ec70efa668ffd1bc01cddc/src/main/java/com/github/koraktor/mavanagaiata/git/jgit/JGitRepository.java)) is printed twice as it contains inner classes and the formatter seems to be unable to handle this, trying to merge the classes’ coverage data.

**Comment by pbrisbin** [comment]
Thanks for the report @koraktor, sorry for the trouble. We'll look into this as soon as we can.

**Comment by ale7714** [comment]
@koraktor 👋  a fix is in progress on this [PR](https://github.com/codeclimate/test-reporter/pull/206) to address this issue. Can you share with us your `cobertura/coverage.xml` file? I would like to do some more testing.

**Comment by koraktor** [comment]
I’ve seen that #206 is already merged. Do you still need my Cobertura output?

Is this already available in the release from https://codeclimate.com/downloads/test-reporter/?

**Comment by ale7714** [comment]
@koraktor the changes were released on the version `0.1.13`. If you're using `latest` release, you will get those changes. You can download latest from https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64. 
If the issues you were seeing aren't solved by this release, it would be really helpful to have your Cobertura output.

**Comment by koraktor** [comment]
No, seems like #206 didn’t fix my problem. The error is still the same.

```sh
$ ./cc-test-reporter --version
Code Climate Test Reporter 0.1.13 (acc7b6c5f273661805ebcf5ad323edd18e45c21e @ 2017-07-26T16:46:47+0000)
```

Here’s a zipped version of my `coverage.xml`: [coverage.zip](https://github.com/codeclimate/test-reporter/files/1181017/coverage.zip)

**Comment by ale7714** [comment]
@koraktor thanks for sharing your `coverage.xml`. We're looking into this.

**Comment by ale7714** [comment]
@koraktor we just release a new version [`0.1.14`](https://github.com/codeclimate/test-reporter/blob/master/CHANGELOG.md#v0114-2017-08-02) that addresses your issue. 
Being able to inspect your `Cobertura` file was really helpful. Thank you!

**Comment by koraktor** [comment]
Thanks for the fix.
